name: hooks

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/hooks.yaml
      - packages/hooks/**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Install Dependencies
        run: yarn install --no-cache --network-timeout 86400000
        working-directory: ./packages/hooks
        env:
          NODE_TOKEN: ${{ secrets.NODE_TOKEN }}
      - name: Unit Test
        run: yarn test
        working-directory: ./packages/hooks
        env:
          NODE_TOKEN: ${{ secrets.NODE_TOKEN }}
      - name: Build Package
        run: yarn build
        working-directory: ./packages/hooks
        env:
          NODE_TOKEN: ${{ secrets.NODE_TOKEN }}
      - name: Publish Package
        run: yarn publish
        working-directory: ./packages/hooks
        env:
          NODE_TOKEN: ${{ secrets.NODE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_TOKEN }}
